### ansible-playbook  emacs_deps.yml  ###

- hosts: all
  pre_tasks:
   - name: Update apt cache
     apt: update_cache=yes
     become: yes

# download git emacs repo
# copy symlinks
  tasks:
   - name: Install ansible apt helpers
     apt:
        name: python-apt
        state: present
     become: yes

   - name: Install clang irony dependencies
     apt:
        name: "{{ packages }}"
        state: present
     vars:
        packages:
        - libclang-dev
        - clang
        - cmake
        - python3-pip
        - cppcheck
        - autotools-dev
        - valgrind
     become: yes

# Python setuptools
   - name: Install python-setuptools (needed for pip)
     apt:
        name: python-setuptools
        state: present
     become: yes

   # Python packages
   - name: Install pip2 emacs plugin deps
     pip:
        name:
          - edi
          - flake8
          - importmagic
          - autopep8

   # install for pip3 as well
   - name: Install pip3 equivalents
     pip:
        name:
          - edi
          - flake8
          - importmagic
          - autopep8
        executable: pip3
